# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "NBR-${datamodule.dataset}"
  # name: 
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  entity: "cnut1648"  # set to name of your wandb team
  # set to True to upload checkpoint
  log_model: False
  # prefix: ""
  # job_type: "train"
  group: null
  tags: []