_target_: src.datamodules.chemprot.DataModule

data_dir: ${data_dir}/chemprot_hf
adaptive_neg_sample: False
use_new_mask: True

batch_size: 64
num_workers: 10
pin_memory: True

# for logging
dataset: chemprot